# -*- coding: utf-8 -*-
"""Q 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KnKDjMHWr_zqlGydQneKvWNkCKemXJV
"""

from google.colab import files
uploaded = files.upload()

# Step 1: Install libraries
!pip install opencv-python matplotlib

# Step 2: Import libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 3: Upload image
from google.colab import files
uploaded = files.upload()

# Step 4: Read image
img_path = list(uploaded.keys())[0]
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -----------------------------
# Step 5: Simulate Distortions
# -----------------------------

# (a) Add Gaussian Noise (Sensor noise)
noise = np.random.normal(0, 25, img.shape).astype(np.uint8)
noisy_img = cv2.add(img, noise)

# (b) Blur (Optical defocus)
blur_img = cv2.GaussianBlur(noisy_img, (9,9), 0)

# (c) Downsample (Low resolution / sampling issue)
small = cv2.resize(blur_img, (img.shape[1]//4, img.shape[0]//4))
distorted_img = cv2.resize(small, (img.shape[1], img.shape[0]))

# -----------------------------
# Step 6: Improvements
# -----------------------------

# (a) Denoising
denoised = cv2.fastNlMeansDenoisingColored(distorted_img, None, 10, 10, 7, 21)

# (b) Sharpening (restore edges)
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
sharpened = cv2.filter2D(denoised, -1, kernel)

# -----------------------------
# Step 7: Show Results
# -----------------------------
plt.figure(figsize=(12,6))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(distorted_img)
plt.title("Distorted Image")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(sharpened)
plt.title("Improved Image")
plt.axis('off')

plt.show()