# -*- coding: utf-8 -*-
"""EXP 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KnKDjMHWr_zqlGydQneKvWNkCKemXJV
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Get the filename of the uploaded image
image_filename = list(uploaded.keys())[0]

# Read image using the correct filename
img = cv2.imread(os.path.join('/content/', image_filename))

# Check if image was loaded successfully
if img is None:
    print(f"Error: Could not load image '{image_filename}'. Please check the file path and ensure the image exists.")
else:
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Create kernel
    kernel = np.ones((5,5), np.uint8)

    # Apply dilation
    dilated = cv2.dilate(gray, kernel, iterations=1)

    # Display images
    titles = ['Original (Grayscale)', 'Dilated']
    images = [gray, dilated]

    plt.figure(figsize=(10, 5))
    for i in range(2):
        plt.subplot(1,2,i+1)
        plt.imshow(images[i], cmap='gray')
        plt.title(titles[i])
        plt.axis('off')

    plt.tight_layout()
    plt.show()